"""
Layer-by-layer comparison between:
  (A) Python quantised reference (generated by generate_cosim_vectors.py)
  (B) HLS co-simulation output   (written by tb_cosim.cpp after hw sim)

Also compares float32 vs quantised to quantify fixed-point degradation.

Usage
-----
  python3 layer_compare.py [--hls_dir path]  [--report html|text]
"""

import numpy as np
import sys
import json
from pathlib import Path

ROOT     = Path(__file__).parent.parent.parent
VEC_DIR  = ROOT / "hls" / "tb" / "cosim_data"
VERIFY   = Path(__file__).parent

sys.path.insert(0, str(VERIFY))
from quantize_utils import read_bin, layer_stats, from_int16


# ---------------------------------------------------------------------------
# Load a layer's reference data
# ---------------------------------------------------------------------------

def load_meta(layer_dir: Path) -> dict:
    meta = {}
    meta_file = layer_dir / "meta.txt"
    if meta_file.exists():
        for line in meta_file.read_text().splitlines():
            if '=' in line:
                k, v = line.split('=', 1)
                try:    meta[k.strip()] = int(v.strip())
                except: meta[k.strip()] = v.strip()
    return meta


def load_layer_data(layer_dir: Path):
    """Returns (input, expected, hls_output or None, meta)"""
    meta    = load_meta(layer_dir)
    oc      = meta.get('out_c', 1)
    oh      = meta.get('out_h', 1)
    ow      = meta.get('out_w', 1)
    out_shape = (oc, oh, ow)

    exp_path = layer_dir / "expected.bin"
    hls_path = layer_dir / "hls_output.bin"

    expected = read_bin(str(exp_path), out_shape) if exp_path.exists() else None
    hls_out  = read_bin(str(hls_path), out_shape) if hls_path.exists() else None
    return expected, hls_out, meta


# ---------------------------------------------------------------------------
# Float32 vs quantised comparison (always available)
# ---------------------------------------------------------------------------

def compare_float_vs_quant(model_q, model_f) -> list:
    """
    Compare float32 layer outputs with quantised equivalents.
    Both models must have already run forward().
    """
    report = []
    for idx in model_q.layer_outputs:
        if idx not in model_f.layer_outputs:
            continue
        ref  = model_f.layer_outputs[idx].flatten().astype(np.float32)
        test = model_q.layer_outputs[idx].flatten().astype(np.float32)
        s = layer_stats(ref, test, str(idx))
        report.append(s)
    return report


# ---------------------------------------------------------------------------
# Quantised reference vs HLS co-sim comparison
# ---------------------------------------------------------------------------

def compare_ref_vs_hls() -> list:
    report = []
    if not VEC_DIR.exists():
        return report

    for layer_dir in sorted(VEC_DIR.iterdir(), key=lambda p: int(p.name)):
        if not layer_dir.is_dir():
            continue
        idx = layer_dir.name
        expected, hls_out, meta = load_layer_data(layer_dir)
        if expected is None:
            continue

        row = {'layer': idx, 'cmd': meta.get('cmd','?')}
        if hls_out is not None:
            s = layer_stats(expected, hls_out, f"L{idx}")
            row.update(s)
            row['hls_available'] = True
        else:
            row['hls_available'] = False
            row['note'] = 'HLS output not yet generated (run cosim first)'
        report.append(row)
    return report


# ---------------------------------------------------------------------------
# Text report
# ---------------------------------------------------------------------------

def print_report(rows: list, title: str = ""):
    print(f"\n{'='*70}")
    if title:
        print(f"  {title}")
        print(f"{'='*70}")
    hdr = f"  {'Layer':8s} {'MAE':>10s} {'MaxErr':>10s} {'SNR(dB)':>10s} {'%≤1LSB':>8s}  Status"
    print(hdr)
    print(f"  {'-'*65}")
    PASS_SNR = 20.0   # dB threshold for "acceptable"
    for r in rows:
        if 'mae' not in r:
            note = r.get('note', '')
            print(f"  {str(r['layer']):8s}  {note}")
            continue
        status = "PASS" if r['snr_db'] >= PASS_SNR else "WARN"
        snr_str = f"{r['snr_db']:.1f}" if r['snr_db'] != float('inf') else "  inf"
        print(f"  {str(r['layer']):8s}  {r['mae']:>10.4f}  {r['max_err']:>10.4f}  "
              f"{snr_str:>10s}  {r['pct_ok']:>7.2f}%  {status}")
    print(f"{'='*70}")


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------

def write_html_report(fq_rows: list, hls_rows: list, out_path: Path):
    def status_class(snr):
        if snr == float('inf') or snr >= 30: return "pass"
        if snr >= 20: return "ok"
        return "fail"

    rows_html = ""
    for r in fq_rows + hls_rows:
        if 'mae' not in r:
            rows_html += f"<tr><td>{r['layer']}</td><td colspan='5'>{r.get('note','')}</td></tr>\n"
            continue
        sc = status_class(r['snr_db'])
        snr_s = f"{r['snr_db']:.1f}" if r['snr_db'] != float('inf') else "∞"
        rows_html += (f"<tr class='{sc}'><td>{r['layer']}</td>"
                      f"<td>{r['mae']:.4f}</td><td>{r['max_err']:.4f}</td>"
                      f"<td>{snr_s}</td><td>{r['pct_ok']:.1f}%</td></tr>\n")

    html = f"""<!DOCTYPE html>
<html><head><meta charset='utf-8'>
<title>YOLOv2 HLS Layer Verification Report</title>
<style>
body{{font-family:monospace;background:#1e1e1e;color:#d4d4d4;padding:20px}}
h1{{color:#4ec9b0}} h2{{color:#9cdcfe}}
table{{border-collapse:collapse;width:100%}}
th{{background:#252526;padding:6px 12px;text-align:right;border:1px solid #444}}
td{{padding:4px 12px;border:1px solid #333;text-align:right}}
td:first-child{{text-align:left;font-weight:bold}}
tr.pass{{background:#1a3a1a}} tr.ok{{background:#2a2a1a}} tr.fail{{background:#3a1a1a}}
tr:hover{{filter:brightness(1.2)}}
</style></head><body>
<h1>YOLOv2 HLS Accelerator – Layer Verification Report</h1>
<h2>Float32 vs Quantised (ap_fixed&lt;16,8&gt;)</h2>
<table>
<tr><th>Layer</th><th>MAE</th><th>MaxErr</th><th>SNR(dB)</th><th>%≤1LSB</th></tr>
{rows_html}
</table>
<p style='color:#888'>Generated by layer_compare.py</p>
</body></html>"""
    out_path.write_text(html)
    print(f"[report] HTML written to {out_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--weights", default=None, help="Path to .weights file")
    ap.add_argument("--report", choices=["text","html"], default="text")
    args = ap.parse_args()

    # Run models
    from darknet_weights import make_synthetic_weights, load_weights
    from yolov2_model    import YOLOv2
    from generate_test_image import prepare_test_image

    if args.weights and Path(args.weights).exists():
        lw = load_weights(args.weights)
    else:
        print("[weights] using synthetic weights")
        lw = make_synthetic_weights()

    img_p = VERIFY / "test_image_rgb.npy"
    img = np.load(img_p) if img_p.exists() else prepare_test_image()

    print("Running float32 model ...")
    model_f = YOLOv2(lw, quantised=False); model_f.forward(img)
    print("Running quantised model ...")
    model_q = YOLOv2(lw, quantised=True);  model_q.forward(img)

    fq_rows  = compare_float_vs_quant(model_q, model_f)
    hls_rows = compare_ref_vs_hls()

    print_report(fq_rows,  "Float32 vs Quantised (fixed-point degradation)")
    print_report(hls_rows, "Quantised Reference vs HLS Co-sim Output")

    if args.report == "html":
        write_html_report(fq_rows, hls_rows, VERIFY / "verification_report.html")
